#index:
#    path: /

#    controller: App\Controller\DefaultController::index
bank_get_qr_code:
    path: '/bank/account/{id}/qrcode'
    controller: 'App\Controller\MetierController::getQrCodeForProduct'
    methods: ['GET']
    requirements:
        id: '\d+'