<?php

namespace ContainerZKswXJA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EL8SLSZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EL8SLSZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EL8SLSZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'raitingRepository' => ['privates', 'App\\Repository\\RaitingRepository', 'getRaitingRepositoryService', true],
        ], [
            'raitingRepository' => 'App\\Repository\\RaitingRepository',
        ]);
    }
}
