<?php

namespace ContainerZKswXJA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ReW_1KVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ReW.1KV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ReW.1KV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'c' => ['privates', 'App\\Repository\\MetierRepository', 'getMetierRepositoryService', true],
        ], [
            'c' => 'App\\Repository\\MetierRepository',
        ]);
    }
}
