<?php

namespace ContainerZKswXJA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SV_UDfTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SV.UDfT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SV.UDfT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'raiting' => ['privates', '.errored..service_locator.SV.UDfT.App\\Entity\\Raiting', NULL, 'Cannot autowire service ".service_locator.SV.UDfT": it references class "App\\Entity\\Raiting" but no such service exists.'],
            'raitingRepository' => ['privates', 'App\\Repository\\RaitingRepository', 'getRaitingRepositoryService', true],
        ], [
            'raiting' => 'App\\Entity\\Raiting',
            'raitingRepository' => 'App\\Repository\\RaitingRepository',
        ]);
    }
}
