<?php

namespace ContainerZKswXJA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LKFr3qvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lKFr3qv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lKFr3qv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sousMetier' => ['privates', '.errored..service_locator.lKFr3qv.App\\Entity\\SousMetier', NULL, 'Cannot autowire service ".service_locator.lKFr3qv": it references class "App\\Entity\\SousMetier" but no such service exists.'],
            'sousMetierRepository' => ['privates', 'App\\Repository\\SousMetierRepository', 'getSousMetierRepositoryService', true],
        ], [
            'em' => '?',
            'sousMetier' => 'App\\Entity\\SousMetier',
            'sousMetierRepository' => 'App\\Repository\\SousMetierRepository',
        ]);
    }
}
