<?php

namespace ContainerZKswXJA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MMgDPTWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mMgDPTW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mMgDPTW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'metier' => ['privates', '.errored..service_locator.mMgDPTW.App\\Entity\\Metier', NULL, 'Cannot autowire service ".service_locator.mMgDPTW": it references class "App\\Entity\\Metier" but no such service exists.'],
            'metierRepository' => ['privates', 'App\\Repository\\MetierRepository', 'getMetierRepositoryService', true],
        ], [
            'metier' => 'App\\Entity\\Metier',
            'metierRepository' => 'App\\Repository\\MetierRepository',
        ]);
    }
}
