<?php

namespace ContainerZKswXJA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S4hD30eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S4hD30e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S4hD30e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'MetierRepository' => ['privates', 'App\\Repository\\SousMetierRepository', 'getSousMetierRepositoryService', true],
        ], [
            'MetierRepository' => 'App\\Repository\\SousMetierRepository',
        ]);
    }
}
