<?php

namespace ContainerZKswXJA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassification2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.l9i_KJf.App\Entity\Classification' shared service.
     *
     * @return \App\Entity\Classification
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.l9i_KJf": it references class "App\\Entity\\Classification" but no such service exists.');
    }
}
