<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OoM3hQIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OoM3hQI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OoM3hQI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sousMetierRepository' => ['privates', 'App\\Repository\\SousMetierRepository', 'getSousMetierRepositoryService', true],
        ], [
            'em' => '?',
            'sousMetierRepository' => 'App\\Repository\\SousMetierRepository',
        ]);
    }
}
