<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KDMa8UwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kDMa8Uw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kDMa8Uw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tache' => ['privates', '.errored..service_locator.kDMa8Uw.App\\Entity\\Tache', NULL, 'Cannot autowire service ".service_locator.kDMa8Uw": it references class "App\\Entity\\Tache" but no such service exists.'],
        ], [
            'tache' => 'App\\Entity\\Tache',
        ]);
    }
}
