<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EFekZBpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EFekZBp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EFekZBp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'annonce' => ['privates', '.errored..service_locator.EFekZBp.App\\Entity\\Annonce', NULL, 'Cannot autowire service ".service_locator.EFekZBp": it references class "App\\Entity\\Annonce" but no such service exists.'],
        ], [
            'annonce' => 'App\\Entity\\Annonce',
        ]);
    }
}
