<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PRT4F6aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pRT4F6a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pRT4F6a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'c' => ['privates', 'App\\Repository\\SousMetierRepository', 'getSousMetierRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'c' => 'App\\Repository\\SousMetierRepository',
            'entityManager' => '?',
        ]);
    }
}
