<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HYh8s5lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HYh8s5l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HYh8s5l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sousMetier' => ['privates', '.errored..service_locator.HYh8s5l.App\\Entity\\SousMetier', NULL, 'Cannot autowire service ".service_locator.HYh8s5l": it references class "App\\Entity\\SousMetier" but no such service exists.'],
        ], [
            'sousMetier' => 'App\\Entity\\SousMetier',
        ]);
    }
}
