<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TTms4P2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TTms4P2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TTms4P2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'raiting' => ['privates', '.errored..service_locator.TTms4P2.App\\Entity\\Raiting', NULL, 'Cannot autowire service ".service_locator.TTms4P2": it references class "App\\Entity\\Raiting" but no such service exists.'],
        ], [
            'raiting' => 'App\\Entity\\Raiting',
        ]);
    }
}
