<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6M5Sy7QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6M5Sy7Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6M5Sy7Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'metierRepository' => ['privates', 'App\\Repository\\MetierRepository', 'getMetierRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'metierRepository' => 'App\\Repository\\MetierRepository',
            'slugger' => '?',
        ]);
    }
}
