<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WpBo1jTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wpBo1jT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wpBo1jT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'id' => ['privates', '.errored..service_locator.wpBo1jT.App\\Entity\\SousMetier', NULL, 'Cannot autowire service ".service_locator.wpBo1jT": it references class "App\\Entity\\SousMetier" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'id' => 'App\\Entity\\SousMetier',
        ]);
    }
}
