<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonce2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EFekZBp.App\Entity\Annonce' shared service.
     *
     * @return \App\Entity\Annonce
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.EFekZBp": it references class "App\\Entity\\Annonce" but no such service exists.');
    }
}
