<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRaiting2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TTms4P2.App\Entity\Raiting' shared service.
     *
     * @return \App\Entity\Raiting
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TTms4P2": it references class "App\\Entity\\Raiting" but no such service exists.');
    }
}
