<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSousMetier3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lKFr3qv.App\Entity\SousMetier' shared service.
     *
     * @return \App\Entity\SousMetier
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lKFr3qv": it references class "App\\Entity\\SousMetier" but no such service exists.');
    }
}
