<?php

namespace ContainerZMknw3x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.d23vQsL.App\Entity\Tache' shared service.
     *
     * @return \App\Entity\Tache
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.d23vQsL": it references class "App\\Entity\\Tache" but no such service exists.');
    }
}
