<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZMknw3x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZMknw3x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZMknw3x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZMknw3x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZMknw3x\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZMknw3x',
    'container.build_id' => '1fa77ca6',
    'container.build_time' => 1683301013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZMknw3x');
