<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBjTAC0B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBjTAC0B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBjTAC0B.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBjTAC0B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBjTAC0B\App_KernelDevDebugContainer([
    'container.build_hash' => 'BjTAC0B',
    'container.build_id' => '71aa4739',
    'container.build_time' => 1683629566,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBjTAC0B');
