<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPYCmbQL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPYCmbQL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPYCmbQL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPYCmbQL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPYCmbQL\App_KernelDevDebugContainer([
    'container.build_hash' => 'PYCmbQL',
    'container.build_id' => '326b6176',
    'container.build_time' => 1683390901,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPYCmbQL');
